### ISSUE TITLE
Mechanical Ventilation of SARS Patients: Lessons from the 2003 SARS Outbreak

### ISSUE THREAD

**Issue by jurra** [CombatCovid/doc-template#10]
## Checklist
*template:* https://github.com/CombatCovid/doc-template
- [ ] Source files put in the `./src` folder
- [ ] Images in `./docs/img` folder
- [ ] In Docs if you are writing in English use the `./docs/EN` folder, otherwise make a `./docs/<Other-Language>` folder
- [ ] README.md with metadata at the root of the repository
- [ ] Add metadata to the Readme.
Ask questions and communicate in our channel, we will assist you:      
#how-to-document-designs: https://discord.gg/zVFR5R

**Comment by SolarCola** [comment]
Uploaded to github: https://github.com/CombatCovid/LearningFromSARS
