### ISSUE TITLE
Open breath

### ISSUE THREAD

**Issue by jurra** [CombatCovid/doc-template#16]
### Documentation checklist for each project
*template:* https://github.com/CombatCovid/doc-template
- [x] Source files put in the `./src` folder
- [x] Images in `./docs/img` folder
- [ ] In Docs if you are writing in English use the `./docs/EN` folder, otherwise make a `./docs/<Other-Language>` folder
- [x] README.md with metadata at the root of the repository
- [x] Add metadata to the Readme.
Ask questions and communicate in our channel, we will assist you:      
#how-to-document-designs: https://discord.gg/zVFR5R

**Comment by josemartinez18** [comment]
Link to the Google Drive: https://drive.google.com/drive/folders/1Ax_DoiQ_XFtQ0hr3tQVxUWuaedPDsY4w?usp=sharing

**Comment by dvr1996** [comment]
Hi! 

We were able to create the folder using the Template. 

Added in pictures and Docs

Also wrote a README.md file 

Only thing we didn't manage to do was to upload to Github. 

Jose thanks a lot! Its great to see what you're doing in these days, RESPECT! 
I enjoyed the workshop :)
