### ISSUE TITLE
EK evaluation kit

### ISSUE THREAD

**Issue by jurra** [CombatCovid/doc-template#18]
https://www.sensirion.com/en/flow-sensors/

### Documentation checklist for each project
*template:* https://github.com/CombatCovid/doc-template
- [x] Source files put in the `./src` folder
- [x] Images in `./docs/img` folder
- [ ] In Docs if you are writing in English use the `./docs/EN` folder, otherwise make a `./docs/<Other-Language>` folder
- [x] README.md with metadata at the root of the repository
- [x] Add metadata to the Readme.
Ask questions and communicate in our channel, we will assist you:      
#how-to-document-designs: https://discord.gg/zVFR5R

- [x] Github upload

**Comment by jurra** [comment]
here is my drive link, or dropbox link

**Comment by mariespecht** [comment]
Here is our drive link!
https://drive.google.com/open?id=1aH1R2BOcrtRLyJXiKl_RZmv3_Lv0Lim5
