### ISSUE TITLE
Venturi flow drivers

### ISSUE THREAD

**Issue by dtsoli** [CombatCovid/doc-template#21]
### Documentation checklist for each project
*template:* https://github.com/CombatCovid/doc-template
- [x] Repo uploaded in github
- [x] Source files put in the `./src` folder
- [x] Images in `./docs/img` folder
- [ ] In Docs if you are writing in English use the `./docs/EN` folder, otherwise make a `./docs/<Other-Language>` folder
- [ ] README.md with metadata at the root of the repository
- [ ] Add metadata to the Readme.
Ask questions and communicate in our channel, we will assist you:      
#how-to-document-designs: https://discord.gg/zVFR5R

**Comment by dtsoli** [comment]
Here I attach the google drive file with the information I managed to retrieve. There was no clear project at the resources, so I tried my best to find relevant information. I hope I helped and wish you good luck! **https://drive.google.com/open?id=1jtAB0oQbWocGqET6p7NftV99wlgV1Mb9**
Here are some more articles I found:
https://www.3dprintingmedia.network/covid-19-3d-printed-valve-for-reanimation-device/
https://www.3dprintingmedia.network/forums/topic/charlotte-valve-by-isinnova-for-non-invasive-ventilator/page/3/
https://www.3dnatives.com/en/italy-patients-covid-19-170320205/
https://www.weforum.org/agenda/2020/03/3d-printed-emergency-breathing-valves-covid-19/
https://www.3dnatives.com/en/italy-patients-covid-19-170320205/
https://www.medicaldevice-network.com/news/3d-printed-valves-covid-19-italy/

**Comment by jurra** [comment]
Great thank you!!! Will look into that :)

**Comment by jurra** [comment]
The documentation is incomplete, without metadata the repository is not visible findable.
This one goes back to in progress.

**Comment by leilaicruz** [comment]
Venturi flow drivers do not have a clear project to base our documentation. Also there is not clear open source design to start replicating

**Comment by leilaicruz** [comment]
- [x] In Docs if you are writing in English use the ./docs/EN folder, otherwise make a ./docs/<Other-Language> folder
 - [x] README.md with metadata at the root of the repository
