### ISSUE TITLE
COVID-19 MEDICAL FACE SHIELD- University of Wisconsin-Madison design

### ISSUE THREAD

**Issue by leilaicruz** [CombatCovid/doc-template#4]
Link where there is all the information to document : [https://making.engr.wisc.edu/shield/](https://making.engr.wisc.edu/shield/)

### Documentation checklist for each project
*template:* https://github.com/CombatCovid/doc-template
- [ ] Source files put in the `./src` folder
- [ ] Images in `./docs/img` folder
- [ ] In Docs if you are writing in English use the `./docs/EN` folder, otherwise make a `./docs/<Other-Language>` folder
- [ ] README.md with metadata at the root of the repository
- [ ] Add metadata to the Readme.
Ask questions and communicate in our channel, we will assist you:      
#how-to-document-designs: https://discord.gg/zVFR5R

**Comment by leilaicruz** [comment]
Medically approved, ready for manufacture, vinyl with foam forehead pad, all McMaster materials, developed at University of Wisconsin.

**Comment by Jurrvr** [comment]
- [x]  Source files put in the ./src folder
- [x]   Images in ./docs/img folder
- [x]   In Docs if you are writing in English use the ./docs/EN folder, otherwise make a ./docs/<Other-Language> folder
- [x]   README.md with metadata at the root of the repository
- [ ]   Add metadata to the Readme.

**Comment by Jurrvr** [comment]
Link to drive: https://drive.google.com/open?id=1mgUA6NLsfJZA2xvONQKhLHrqyHMl80N3
Still have to look at the docs, tried to write/copy the instructions from the project, links to images are in md format but didn't succeed to push to git

**Comment by leilaicruz** [comment]
- [x] Download the drive folder of the project and create the repository
- [x] Add the metadata.yml file
