### ISSUE TITLE
OxyGEN ventilators: 2 versions with very complete information.

### ISSUE THREAD

**Issue by JannesHN** [CombatCovid/doc-template#6]
### Documentation checklist for each project
*template:* https://github.com/CombatCovid/doc-template
- [x] Pushed to github
- [x] Source files put in the `./src` folder
- [x] Images in `./docs/img` folder
- [ ] In Docs if you are writing in English use the `./docs/EN` folder, otherwise make a `./docs/<Other-Language>` folder
- [ ] README.md with metadata at the root of the repository
- [x] Add metadata to the Readme.
Ask questions and communicate in our channel, we will assist you:      
#how-to-document-designs: https://discord.gg/zVFR5R

https://github.com/ProtofyTeam/OxyGEN
They have two types of ventilators. Ones that actually seem to pass hospital tests. Very complete information already, just needs to be structured in our in template for readability. Easy starter.

**Comment by MegaRaccoon21** [comment]
https://drive.google.com/open?id=1QPZN5m0zD9chLsvYgrZulOWv9Xj8cKbi

**Comment by jurra** [comment]
Promising project nice content, poorly documented and confusing, two projects nested in one, that needs to be fixed. Also there is no metadata which agains misses the point of findability and accessibility. Also in docs there are no mardkwon files explaining the content, because some are in pdf.

**Comment by leilaicruz** [comment]
metadata and front image added, still lacking markdown clear documentation
